declare const styles: {
  attachmentViewer: string;
  header: string;
  title: string;
  summary: string;
  summaryCards: string;
  summaryCard: string;
  cardIcon: string;
  cardValue: string;
  cardLabel: string;
  toolbar: string;
  content: string;
  categorySection: string;
  categoryTitle: string;
  attachmentsList: string;
  attachmentItem: string;
  attachmentIcon: string;
  attachmentInfo: string;
  fileName: string;
  fileSize: string;
  uploadDate: string;
  attachmentActions: string;
  actionButton: string;
  emptyState: string;
  emptyIcon: string;
  emptyText: string;
  fileIcon: string;
  fileNameCell: string;
  filesContainer: string;
  filesList: string;
};

export default styles;
